---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  labels:
    
    opentelemetry.io/name: llm
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: llm
    app.kubernetes.io/name: llm
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      opentelemetry.io/name: llm
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: llm
        
        app.kubernetes.io/version: "2.2.0"
        app.kubernetes.io/component: llm
        app.kubernetes.io/name: llm
      annotations:
        resource.opentelemetry.io/service.namespace: otel-demo
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: llm
          image: '655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/llm:21671988713'
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 8000
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: otel-collector
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: FLAGD_HOST
              value: flagd
            - name: FLAGD_PORT
              value: "8013"
          resources:
            null
          volumeMounts:
      volumes: