# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/currency
  tag: "21947916886"

resources:
  requests:
    cpu: 100m
    memory: 15Mi
  limits:
    cpu: 300m
    memory: 20Mi

swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10