# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/currency
  tag: "22304153411"
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: 20Mi
