# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/currency
  tag: "22037152309"
resources:
  requests:
    cpu: 30m
    memory: 10Mi
  limits:
    cpu: 30m
    memory: 10Mi
swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10
