# Default values for load-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/load-generator
  tag: "22060391080"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu:
    memory: 512Mi
swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10
