# Default values for load-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/load-generator
  tag: "21947916815"

resources:
  requests:
    cpu: 800m
    memory: 1000Mi
  limits:
    cpu: 2000m
    memory: 1500Mi

swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10