# Default values for checkout.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/checkout
  tag: "22037152333"
resources:
  requests:
    cpu: 30m
    memory: 20Mi
  limits:
    cpu: 30m
    memory: 20Mi
swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10
