---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service
metadata:
  name: llm
  namespace: {{ .Values.namespace }}
  labels:
    
    opentelemetry.io/name: llm
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: llm
    app.kubernetes.io/name: llm
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: 8000
      name: tcp-service
      targetPort: 8000
  selector:
    
    opentelemetry.io/name: llm