# Default values for accounting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/accounting
  tag: "21986527908"
resources:
  requests:
    cpu: 100m
    memory: 80Mi
  limits:
    cpu: 300m
    memory: 120Mi
swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10
