# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu:
    memory: 128Mi

swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10