# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources:
  requests:
    cpu: 400m
    memory: 75Mi
  limits:
    cpu: 1000m
    memory: 100Mi

swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10