# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/frontend
  tag: "22037152315"
resources:
  requests:
    cpu: 400m
    memory: 250Mi
  limits:
    cpu: 400m
    memory: 250Mi
swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10
