# Default values for payment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/payment
  tag: "21947916807"

resources:
  requests:
    cpu: 200m
    memory: 100Mi
  limits:
    cpu: 800m
    memory: 140Mi

swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10