# Default values for payment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/payment
  tag: "22060391053"
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu:
    memory: 256Mi
swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10
