# Default values for product-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/product-catalog
  tag: "22060391101"
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: 20Mi
swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10
