---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service
metadata:
  name: ad
  namespace: {{ .Values.namespace }}
  labels:
    
    opentelemetry.io/name: ad
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: ad
    app.kubernetes.io/name: ad
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: tcp-service
      targetPort: 8080
  selector:
    
    opentelemetry.io/name: ad