# Default values for valkey-cart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo

resources:
  requests:
    cpu: 40m
    memory: 20Mi
  limits:
    cpu: 40m
    memory: 20Mi

swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10