# Default values for valkey-cart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources:
  requests:
    cpu: 150m
    memory: 15Mi
  limits:
    cpu: 400m
    memory: 20Mi

swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10