---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
  labels:
    
    opentelemetry.io/name: postgresql
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      opentelemetry.io/name: postgresql
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: postgresql
        
        app.kubernetes.io/version: "2.2.0"
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/name: postgresql
      annotations:
        io.opentelemetry.discovery.metrics/config: |
          username: root
          password: otel
          metrics:
            postgresql.blks_hit:
              enabled: true
            postgresql.blks_read:
              enabled: true
            postgresql.tup_fetched:
              enabled: true
            postgresql.tup_returned:
              enabled: true
            postgresql.tup_inserted:
              enabled: true
            postgresql.tup_updated:
              enabled: true
            postgresql.tup_deleted:
              enabled: true
            postgresql.deadlocks:
              enabled: true
          tls:
            insecure: true
        io.opentelemetry.discovery.metrics/enabled: "true"
        io.opentelemetry.discovery.metrics/scraper: postgresql
        resource.opentelemetry.io/service.namespace: otel-demo
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: postgresql
          image: 'postgres:17.6'
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 5432
              name: service
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: otel
            - name: POSTGRES_DB
              value: otel
          resources:
            {{- with .Values.resources }}
            requests:
              cpu: {{ .requests.cpu }}
              memory: {{ .requests.memory }}
            limits:
              cpu: {{ .limits.cpu }}
              memory: {{ .limits.memory }}
            {{- end }}
          volumeMounts:
            - name: postgresql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgresql-init
          configMap:
            name: postgresql-init