---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    
    opentelemetry.io/name: postgresql
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: tcp-service
      targetPort: 5432
  selector:
    
    opentelemetry.io/name: postgresql