# Default values for flagd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/flagd
  tag: "22037152337"
flagd:
  resources:
    requests:
      cpu: 30m
      memory: 80Mi
    limits:
      cpu: 30m
      memory: 80Mi

flagd_ui:
  resources:
    requests:
      cpu: 40m
      memory: 120Mi
    limits:
      cpu: 40m
      memory: 120Mi

swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10
