# Default values for flagd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/flagd
  tag: "22060391052"
flagd:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu:
      memory: 128Mi
flagd_ui:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 
      memory: 512Mi
swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10
