# Default values for flagd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/flagd
  tag: "21947916774"

flagd:
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 300m
      memory: 75Mi

flagd-ui:
  resources:
    requests:
      cpu: 150m
      memory: 180Mi
    limits:
      cpu: 500m
      memory: 250Mi

swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10