# Default values for flagd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/flagd
  tag: "22089612171"
flagd:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu:
      memory: 512Mi
flagd_ui:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu:
      memory: 512Mi
swan_hpa:
  swan_minReplicas: 2
  swan_maxReplicas: 10
