---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-provider
  labels:
    
    opentelemetry.io/name: image-provider
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: image-provider
    app.kubernetes.io/name: image-provider
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      opentelemetry.io/name: image-provider
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: image-provider
        
        app.kubernetes.io/version: "2.2.0"
        app.kubernetes.io/component: image-provider
        app.kubernetes.io/name: image-provider
      annotations:
        io.opentelemetry.discovery.metrics/config: |
          endpoint: "http://`endpoint`/status"
          collection_interval: "10s"
          timeout: "20s"
        io.opentelemetry.discovery.metrics/enabled: "true"
        io.opentelemetry.discovery.metrics/scraper: nginx
        resource.opentelemetry.io/service.namespace: otel-demo
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: image-provider
          image: '655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/image-provider:21671988731'
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 8081
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: otel-collector
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: IMAGE_PROVIDER_PORT
              value: "8081"
            - name: OTEL_COLLECTOR_PORT_GRPC
              value: "4317"
            - name: OTEL_COLLECTOR_HOST
              value: $(OTEL_COLLECTOR_NAME)
          resources:
            limits:
              memory: 50Mi
          volumeMounts:
      volumes: