# Default values for ad.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: otel-demo
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/ad
  tag: "22304153410"
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: 300Mi
