---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: {{ .Values.namespace }}
  labels:
    
    opentelemetry.io/name: shipping
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: shipping
    app.kubernetes.io/name: shipping
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      opentelemetry.io/name: shipping
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: shipping
        
        app.kubernetes.io/version: "2.2.0"
        app.kubernetes.io/component: shipping
        app.kubernetes.io/name: shipping
      annotations:
        resource.opentelemetry.io/service.namespace: otel-demo
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: shipping
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 8080
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: otel-collector
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: SHIPPING_PORT
              value: "8080"
            - name: QUOTE_ADDR
              value: http://quote:8080
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_NAME):4317
            - name: IPV6_ENABLED
              value: "false"
          resources:
            {{- with .Values.resources }}
            requests:
              cpu: {{ .requests.cpu }}
              memory: {{ .requests.memory }}
            limits:
              cpu: {{ .limits.cpu }}
              memory: {{ .limits.memory }}
            {{- end }}
          volumeMounts:
      volumes: