# Default values for email.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/swan_polyglot-microservices-application/email
  tag: "21986527874"
resources:
  requests:
    cpu: 150m
    memory: 70Mi
  limits:
    cpu: 500m
    memory: 100Mi
swan_hpa:
  swan_minReplicas: 1
  swan_maxReplicas: 10
