name: accounting

on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/accounting/**'
    paths-ignore:
      - 'swan_kubernetes/**'
  pull_request:
    branches:
      - main
    #paths:
    #  - 'src/accounting/**'
    paths-ignore:
      - 'swan_kubernetes/**'
  workflow_dispatch:

jobs:
  swan_docker:
    uses: ./.github/workflows/swan_docker.yml
    with:
      swan_ecr_repository: "swan_polyglot-microservices-application/accounting"
      swan_dockerfile_path: "src/accounting/Dockerfile"
    secrets:
      SWAN_CI_ROLE_ARN: ${{ secrets.SWAN_CI_ROLE_ARN }}