name: checkout

on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/checkout/**'
  pull_request:
    branches:
      - main
    #paths:
    #  - 'src/checkout/**'
  workflow_dispatch:

jobs:
  swan_docker:
    uses: ./.github/workflows/swan_docker.yml
    with:
      swan_ecr_repository: "swan_polyglot-microservices-application/checkout"
      swan_dockerfile_path: "/src/checkout/Dockerfile"
    secrets:
      SWAN_CI_ROLE_ARN: ${{ secrets.SWAN_CI_ROLE_ARN }}