name: currency

on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/currency/**'
  pull_request:
    branches:
      - main
    #paths:
    #  - 'src/currency/**'
  workflow_dispatch:

jobs:
  swan_docker:
    uses: ./.github/workflows/swan_docker.yml
    with:
      swan_ecr_repository: "swan_polyglot-microservices-application/currency"
      swan_dockerfile_path: "/src/currency/Dockerfile"
    secrets:
      SWAN_CI_ROLE_ARN: ${{ secrets.SWAN_CI_ROLE_ARN }}