name: flagd

on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/flagd-ui/**'
  pull_request:
    branches:
      - main
    #paths:
    #  - 'src/flagd-ui/**'
  workflow_dispatch:

jobs:
  swan_docker:
    uses: ./.github/workflows/swan_docker.yml
    with:
      swan_ecr_repository: "swan_polyglot-microservices-application/flagd"
      swan_dockerfile_path: "src/flagd-ui/Dockerfile"
    secrets:
      SWAN_CI_ROLE_ARN: ${{ secrets.SWAN_CI_ROLE_ARN }}