name: fraud-detection

on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/fraud-detection/**'
  pull_request:
    branches:
      - main
    #paths:
    #  - 'src/fraud-detection/**'
  workflow_dispatch:

jobs:
  swan_docker:
    uses: ./.github/workflows/swan_ci.yml
    with:
      swan_ecr_repository: "swan_polyglot-microservices-application/fraud-detection"
      swan_dockerfile_path: "src/fraud-detection/Dockerfile"
      swan_k8s_manifest_path: "swan_kubernetes/fraud-detection/deployment.yaml"
    secrets:
      SWAN_CI_ROLE_ARN: ${{ secrets.SWAN_CI_ROLE_ARN }}