name: load-generator

on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/load-generator/**'
    paths-ignore:
      - 'swan_kubernetes/swan_helm/swan_microservices/**/values.yaml'
  pull_request:
    branches:
      - main
    #paths:
    #  - 'src/load-generator/**'
    paths-ignore:
      - 'swan_kubernetes/swan_helm/swan_microservices/**/values.yaml'
  workflow_dispatch:

jobs:
  swan_docker:
    uses: ./.github/workflows/swan_docker.yml
    with:
      swan_ecr_repository: "swan_polyglot-microservices-application/load-generator"
      swan_dockerfile_path: "src/load-generator/Dockerfile"
    secrets:
      SWAN_CI_ROLE_ARN: ${{ secrets.SWAN_CI_ROLE_ARN }}