name: load-generator

on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/load-generator/**'
  pull_request:
    branches:
      - main
    #paths:
    #  - 'src/load-generator/**'
  workflow_dispatch:

jobs:
  swan_docker:
    uses: ./.github/workflows/swan_ci.yml
    with:
      swan_ecr_repository: "swan_polyglot-microservices-application/load-generator"
      swan_dockerfile_path: "src/load-generator/Dockerfile"
      swan_k8s_manifest_path: "swan_kubernetes/load-generator/deployment.yaml"
    secrets:
      SWAN_CI_ROLE_ARN: ${{ secrets.SWAN_CI_ROLE_ARN }}